language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - python3 -c "import nltk; nltk.download('punkt'); nltk.download('wordnet')"
# command to run tests
script:
  - nosetests
  - coverage run --source=tpclassifier setup.py test
after_success:
  - coveralls